# Generated by Django 4.0.4 on 2022-05-24 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_product_brand_alter_product_product_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_placed',
            old_name='Customr',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='Customr',
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
